### ISSUE TITLE
dynare help

### ISSUE THREAD

**Issue by fhosseini** [JohannesPfeifer/DSGE_mod#1]
Dear all,
I am trying to extend the model in dynare! If I only want a single one with all two or three shocks at once, what I should do? I want to interpret all three shocks for, for example  monetary , fiscal and oil price, at once. 
Thanks a lot in advance
fhosseini

**Comment by JohannesPfeifer** [comment]
@fhosseini That is a Dynare question you should pose at the Dynare forum at http://www.dynare.org/phpBB3/
As it is not related to the codes I am providing in this repository, I am closing the ticket.
