### ISSUE TITLE
SMM Dynare Toolbox with Binomial draws

### ISSUE THREAD

**Issue by Daniel2021333** [JohannesPfeifer/DSGE_mod#13]
Hi,

I am trying to estimate by SMM with the relatively new Dynare toolbox a model with two binomial draws (a couple of random draws into the model will do the job). In fact, the binomial parameters, say p and q, are those among I would like to be estimated. Nonetheless, to the best of my understanding Dynare only supports normal shocks for the estimations. 

Is there a way to generate random draws as opposed to Normal ones for the estimation in the SMM toolbox? 

Alternatively, I was thinking whether there is a Dynare-implementable method to transform normal to random shocks (into the model part of the code) so that I can proceed with the SMM estimation.

Any help will be highly appreciated!

**Comment by wmutschl** [comment]
Please post on the Dynare forum, I‘ll answer there.

**Comment by JohannesPfeifer** [comment]
Moved to https://forum.dynare.org/t/smm-dynare-toolbox-with-binomial-draws/20849
