### ISSUE TITLE
mode_file Smets and Wouters

### ISSUE THREAD

**Issue by Donkeyfish87** [JohannesPfeifer/DSGE_mod#5]
The mode_file is taken for granted as input in the Smets & Wouters code. If I understand correctly it's obtained from `M_.params` and `M_.Sigma_e` from an initial run of the model without the Metropolis-Hastings algo. Then that is saved as a mode-file and used as input in the code with mode_file option and mode_compute = 0 with MH.

However, it's not clear how this mode_file is retrieved. I.e. which of the mode_compute options is used to retrieve the mode_file. I experimented a bit and believe it uses the default mode_compute = 4, which I would suggest is added to the documentation (if I didn't miss this) or as a step programatically.

**Comment by JohannesPfeifer** [comment]
No, the mode-file is the one supplied by Smets/Wouters in their replication files. I have no insights in how they obtained it. After all, they used Dynare 3.64.

**Comment by Donkeyfish87** [comment]
Ah ok, they've perhaps documented it somewhere (although I didn't find it reading their replication documentation).

If it's not part of the paper perhaps it's natural it's not part of the replication. For completeness it'd be nice though.
