### ISSUE TITLE
Ascari Sbordone 2014_ Issue in line 172

### ISSUE THREAD

**Issue by irfanali88** [JohannesPfeifer/DSGE_mod#7]
Dear Sir, I am running the file Ascari Sbordone 2014 using code available at the website. It shows the following error 

Error using dynare (line 172)
dynare:: can't open Ascari.mod

please comments 
Thank you

**Comment by JohannesPfeifer** [comment]
That is not a problem with the mod-file itself. And you did not provide the full error message. Did you correctly modify your current directory to where the mod-file is located?
