### ISSUE TITLE
Gali and Monacelli (2005) mod file error

### ISSUE THREAD

**Issue by edugca** [JohannesPfeifer/DSGE_mod#8]
Hi Johannes,

In Gali and Monacelli (5005) mod file, there is an error in the line 341. I'm using MatLab 2020a and Dynare 4.6.3. The variable var_string is a cell array, and var_string(var_iter) returns a cell, which results in an error. I believe a fix would be to replace var_string{var_iter} by var_string{var_iter}.

Best,
Eduardo

**Comment by JohannesPfeifer** [comment]
@edugca Are you working with an old version of the file or the 4.5 branch version? The one at 
https://github.com/JohannesPfeifer/DSGE_mod/blob/master/Gali_Monacelli_2005/Gali_Monacelli_2005.mod
has curly brackets as intended
