### ISSUE TITLE
can not find function

### ISSUE THREAD

**Issue by tulipsliu** [JohannesPfeifer/DSGE_mod#9]
Dear Professor Pfeifer

today ,i download the newest DSGE_mod.zip file;
but the program has wrong. the matlab console reminder these messages:

Unrecognized function or variable 'Create_1_by_4_vola_figures'.

Error in BP2020_CES.driver (line 663)
Create_1_by_4_vola_figures

Error in dynare (line 293)
evalin('base',[fname '.driver']) ;

Error in run_model_IRF_generation_order_4 (line 22)
dynare BP2020_CES -Dsticky_prices=1 -Dsticky_wages=1
 

With the highest respect

                                                            Sincerely yours，
                                                           Daniel Tulips Liu

                                                           BeiJing,China.

**Comment by JohannesPfeifer** [comment]
@tulipsliu Thanks for pointing this out. I pushed the missing files
